### ISSUE TITLE
Asking about the training code.

### ISSUE THREAD

**Issue by TMDTom** [amaha7984/KAN-CUT#2]
Thanks for your nice work. I don't see the train.py file. Can you provide the full version of your code? Thanks a lot.

**Comment by camaarno** [comment]
Nice work!  Also wondering if it would be possible to get the _train,py_ and _test.py_ files thanks

**Comment by sun11711** [comment]
I don't see the train.py and test.py file. Can you provide the full version of your code? Thanks a lot.

**Comment by amaha7984** [comment]
Dear all - I have added those files. Thank You!
